import type { Metadata } from "next";
import { Geist, Geist_Mono, Aboreto, Style_Script } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const aboreto = Aboreto({
  variable : "--font-aboreto",
  subsets : ["latin"],
  weight: "400"
});

const stylescript = Style_Script({
  variable : "--font-stylescript",
  subsets : ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        //className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={` ${stylescript.variable} antialiased`}
      >
        <Header h={"Home"} c={"Contact"} a={"About"} d={"Menu"} e={"Service"}></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
